In [106]:
import numpy as np

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
t = np.array([0, 1, 1, 1])

w = np.random.randn(2)
b = np.random.randn(1)

lr = 0.5

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def forward(X, w, b):
    z = np.dot(X, w) + b
    y = sigmoid(z)
    return y, z

def backward(x, t, y, z):
    derror_y = y - t
    dy_z = y * (1 - y)
    
    dz_w = x
    dz_b = np.ones_like(dy_z)
    
    derror_w = derror_y * dy_z * dz_w.T
    derror_b = derror_y * dy_z * dz_b
    
    return derror_w, derror_b

for i in range(10000):
    y, z = forward(x, w, b)

    error = np.mean(0.5 * (t - y) ** 2)
    
    derror_w1, derror_b = backward(x, t, y, z)
    w -= lr * np.mean(derror_w1)
    b -= lr * np.mean(derror_b)
    if i % 1000 == 0:
        print("Loss after {} epochs: ".format(i), error)

Loss after 0 epochs:  0.06554779476951629
Loss after 1000 epochs:  0.006593842340922963
Loss after 2000 epochs:  0.0030802294823400567
Loss after 3000 epochs:  0.0019620996276469944
Loss after 4000 epochs:  0.0014267677150240185
Loss after 5000 epochs:  0.0011160146144549076
Loss after 6000 epochs:  0.0009141001215924417
Loss after 7000 epochs:  0.0007728121494250107
Loss after 8000 epochs:  0.0006686232178497598
Loss after 9000 epochs:  0.0005887303915044692


In [97]:
np.array([[0, 1]])

array([[0, 1]])

In [98]:
w

array([3.43711838, 3.71247769])

In [104]:
np.dot([[0, 1]], w.T)

array([3.71247769])

In [100]:
w.shape

(2,)