In [182]:
import numpy as np

inputs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

t = np.array([0, 1, 1, 0])

w0 = np.random.rand(2, 2)
b0 = np.random.rand(2)
w1 = np.random.rand(2)
bo = np.random.randn()

In [183]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

In [231]:
h_output = inputs @ w0 + b0
h = sigmoid(h_output)

output = h @ w1 + bo
y = sigmoid(output)

error = np.mean(0.5 * ((target - y) ** 2))

derror_y = y - t
dy_output = output * (1 - output)
doutput = derror_y * dy_output

derror_h = np.dot(np.expand_dims(doutput, 1), np.expand_dims(w1, -1).T)

dh_hiddenw = np.mean(h, axis=0)

derror_hiddenw = derror_h.mean(axis=0) * dh_hiddenw

w1 -= 0.01 * derror_hiddenw

In [232]:
derror_h.shape

(4, 2)

In [189]:
dy_dh.shape

(4, 2)

(4,)

In [230]:
np.dot(np.expand_dims(doutput, 1), np.expand_dims(w1, -1).T)

array([[-0.46137042, -1.10075336],
       [ 0.08869696,  0.21161626],
       [ 0.08657697,  0.20655831],
       [-0.79959043, -1.90769026]])

In [223]:
w1.shape

(2,)

In [269]:
x = [0, 1]
t = [1, 0]

w1 = np.random.randn(1)
b = np.random.randn(1)

def forward(x, w, b):
    z = w * x + b
    y = sigmoid(z)
    return y, z

def backward(x, t, y, z):
    derror_y = y - t
    dy_z = y * (1 - y)
    dz_w = x
    dz_b = np.ones_like(x)
    
    derror_w = np.mean(derror_y * dy_z * dz_w)
    derror_b = np.mean(derror_y * dy_z * dz_b)
    
    return derror_w, derror_b

lr = 0.5

for i in range(1000):
    y, z = forward(x, w1, b)

    error = np.mean(0.5 * (t - y) ** 2)
    
    derror_w1, derror_b = backward(x, t, y, z)
    
    w1 -= lr * derror_w1
    b -= lr * derror_b
    print(error)

0.20750345771106093
0.20509843720127469
0.2026379350598776
0.20012400068783048
0.19755932819742528
0.19494727744318563
0.19229188047181395
0.1895978308878017
0.18687045412546058
0.18411565735634894
0.1813398587258765
0.17854989675610522
0.17575292199408557
0.17295627422087523
0.17016734964430086
0.167393463356672
0.16464171284246887
0.16191884840030824
0.15923115597526388
0.1565843571116092
0.15398352961149261
0.1514330511390412
0.14893656657920784
0.14649697858373545
0.1441164595318818
0.141796482187816
0.13953786569749607
0.13734083324375784
0.1352050776442083
0.1331298313831601
0.13111393795378812
0.12915592188423097
0.1272540553705537
0.1254064199894943
0.12361096247656389
0.1218655440052201
0.12016798277710604
0.11851609002792046
0.11690769977157822
0.11534069275474385
0.11381301518487716
0.1123226928387802
0.11086784116614928
0.1094466719836498
0.10805749731797229
0.10669873090808643
0.1053688878228581
0.1040665825943754
0.10279052621260162
0.10153952227526446
0.10031246253937581

In [272]:
y, _ = forward(1, w1, b)

In [273]:
y

array([0.07484031])

In [274]:
w1

array([-4.79415432])

In [275]:
b

array([2.27954466])